todo:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "todoID"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "todoID"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_TODO_MGMT"
