companyMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "companyId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "snrId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "snrId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_MGMT"
    LocalSecondaryIndexes:
      - IndexName: "LSI_companyId"
        KeySchema:
          - AttributeName: "snrId"
            KeyType: "HASH"
          - AttributeName: "companyId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
companyDeptMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "companyDeptId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_DEPT_MGMT"
    LocalSecondaryIndexes:
      - IndexName: "LSI_companyDeptId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "companyDeptId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
deptApplMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "applicationId"
        AttributeType: "S"
      - AttributeName: "companyDeptId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyDeptId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_DEPT_APPL_MGMT"
    LocalSecondaryIndexes:
      - IndexName: "LSI_companyId"
        KeySchema:
          - AttributeName: "companyDeptId"
            KeyType: "HASH"
          - AttributeName: "companyId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_applicationId"
        KeySchema:
          - AttributeName: "companyDeptId"
            KeyType: "HASH"
          - AttributeName: "applicationId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

applicationCategoryMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "applicationCategoryId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_APPL_CATEGORY"
    LocalSecondaryIndexes:
      - IndexName: "LSI_applicationCategoryId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "applicationCategoryId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

applRoleMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
      - AttributeName: "applRoleId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_APPL_ROLE_MGMT"
    LocalSecondaryIndexes:
      - IndexName: "LSI_applRoleId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "applRoleId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

teamMember:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "teamMemberId"
        AttributeType: "S"
      - AttributeName: "email"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "email"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_TEAM_MBR"
    LocalSecondaryIndexes:
      - IndexName: "LSI_teamMemberId"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
          - AttributeName: "teamMemberId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

applTeamMemberMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "teamMemberId"
        AttributeType: "S"
      - AttributeName: "managerId"
        AttributeType: "S"
      - AttributeName: "companyDeptId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
      - AttributeName: "email"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_APPL_TEAM_MBR"
    LocalSecondaryIndexes:
      - IndexName: "LSI_companyDeptId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "companyDeptId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_teamMemberId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "teamMemberId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_managerId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "managerId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_email"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "email"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

applTeamMemberRoleMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "teamMemberId"
        AttributeType: "S"
      - AttributeName: "applicationId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_COMPANY_APPL_TEAM_MBR_ROLE"
    LocalSecondaryIndexes:
      - IndexName: "LSI_applicationId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "applicationId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_teamMemberId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "teamMemberId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

teamMemberDetailsMgmt:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "teamMemberDetailsId"
        AttributeType: "S"
      - AttributeName: "clientId"
        AttributeType: "S"
      - AttributeName: "teamMemberId"
        AttributeType: "S"
      - AttributeName: "vendorId"
        AttributeType: "S"
      - AttributeName: "creationDate"
        AttributeType: "S"
      - AttributeName: "companyId"
        AttributeType: "S"
      - AttributeName: "isManager"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "companyId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_TEAM_MBR_X_CLIENT_X_VENDOR"
    LocalSecondaryIndexes:
      - IndexName: "LSI_teamMemberDetailsId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "teamMemberDetailsId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_clientId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "clientId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_teamMemberId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "teamMemberId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_vendorId"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "vendorId"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"
      - IndexName: "LSI_isManager"
        KeySchema:
          - AttributeName: "companyId"
            KeyType: "HASH"
          - AttributeName: "isManager"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

snsAssignmentUpdateTrigger:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: SNS_ASSIGNMENT_UPDATE


snsTeamMemberUpdate:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: SNS_TEAM_MEMBER_UPDATE
